[package]
name = "prompt-builder-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.8.0"
copypasta = "0.10"

[build-dependencies]
slint-build = "1.8.0"
